# Generated by Django 4.2.1 on 2023-08-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_nuquestion_question_image_alter_ourteam_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiimagesQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='question_image')),
            ],
        ),
        migrations.RemoveField(
            model_name='nuquestion',
            name='question_image',
        ),
        migrations.AddField(
            model_name='nuquestion',
            name='question_image',
            field=models.ManyToManyField(to='user.multiimagesquestion'),
        ),
    ]
