# Generated by Django 4.2.1 on 2023-08-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_nuquestion_question_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuquestion',
            name='pdf',
            field=models.FileField(blank=True, upload_to='nu_question'),
        ),
    ]
